import { useEffect, useState } from 'react';
import { DateTime } from 'luxon';
import { ArrowDown, ArrowRight, CalendarDays, Clock3, Globe2, RotateCcw } from 'lucide-react';
import { CopyButton, PageHeading, type Notify } from '../components/common';
import { dateToTimestamp, timestampToDate, TIME_FORMAT, zoneId, zones } from '../core/timestamp';
function attempt<T>(fn: () => T): {value?: T; error?: string} { try { return {value: fn()}; } catch (err) { return {error: (err as Error).message}; } }
export default function TimestampPage({notify}: {notify: Notify}) {
  const [zone, setZone] = useState('Asia/Shanghai');
  const [now, setNow] = useState(Date.now());
  const [stamp, setStamp] = useState('1694419200');
  const [date, setDate] = useState('2026-09-11 10:30:00');
  const [stampReady, setStampReady] = useState(true);
  const [dateReady, setDateReady] = useState(true);
  useEffect(() => { const id = setInterval(() => setNow(Date.now()), 250); return () => clearInterval(id); }, []);
  const current = DateTime.fromMillis(now, {zone: zoneId(zone)});
  const stampResult = stampReady ? attempt(() => timestampToDate(stamp, zone)) : {};
  const dateResult = dateReady ? attempt(() => dateToTimestamp(date, zone)) : {};
  return <div className="tool-page timestamp-page"><PageHeading title="时间戳转换" description="连接机器时间与日常时间。"><label className="zone-select"><Globe2 size={15} /><select aria-label="时区" value={zone} onChange={(e) => setZone(e.target.value)}>{zones.map((z) => <option key={z} value={z}>{z === 'Local' ? 'Local · 系统时区' : z}</option>)}</select></label></PageHeading>
    <div className="timestamp-scroll"><section className="live-clock"><div className="live-clock-title"><span><span className="status-dot" />此刻，现在</span><span className="live-label">LIVE</span></div><div className="clock-grid"><div className="clock-date"><div className="time-label">当前日期时间 <span>{current.toFormat('ZZ')}</span></div><div className="clock-main"><span>{current.toFormat('yyyy-MM-dd')}</span><strong>{current.toFormat('HH:mm:ss')}</strong><CopyButton value={current.toFormat(TIME_FORMAT)} notify={notify} label="复制当前日期时间" /></div></div><div className="clock-stat"><div className="time-label">秒级时间戳</div><div><span>{Math.floor(now / 1000)}</span><CopyButton value={String(Math.floor(now / 1000))} notify={notify} label="复制当前秒级时间戳" /></div></div><div className="clock-stat"><div className="time-label">毫秒级时间戳</div><div><span>{now}</span><CopyButton value={String(now)} notify={notify} label="复制当前毫秒级时间戳" /></div></div></div></section>
    <div className="time-cards"><section className="conversion-card"><div className="conversion-card-heading"><span className="card-icon"><Clock3 size={19} /></span><div><h2>时间戳 <ArrowRight size={15} /> 日期时间</h2><p>自动识别秒级与毫秒级时间戳</p></div></div><form onSubmit={(e) => { e.preventDefault(); setStampReady(true); }}><label htmlFor="timestamp-input">输入时间戳</label><div className="input-with-action"><input id="timestamp-input" aria-label="输入时间戳" placeholder="例如 1694419200" value={stamp} onChange={(e) => { setStamp(e.target.value); setStampReady(false); }} /><button type="button" className="input-link" onClick={() => { setStamp(String(Date.now())); setStampReady(true); }}>此刻</button></div><div className="form-action"><button type="submit" className="button primary">转换为日期时间<ArrowDown size={14} /></button><button type="button" className="icon-button" aria-label="清空时间戳" title="清空" onClick={() => { setStamp(''); setStampReady(false); }}><RotateCcw size={14} /></button></div></form><div className="time-result"><div className="time-label">转换结果 <span>{stampResult.value ? `已识别为${stampResult.value.unit}级` : zone}</span></div>{stampResult.error ? <p className="input-error" role="alert">{stampResult.error}</p> : <><div className="result-main"><span>{stampResult.value?.date ?? '等待转换'}</span><CopyButton value={stampResult.value?.date ?? ''} notify={notify} label="复制日期转换结果" /></div><div className="result-caption">{stampResult.value?.iso ?? '输入时间戳后点击转换'}</div></>}</div></section>
    <section className="conversion-card"><div className="conversion-card-heading"><span className="card-icon violet"><CalendarDays size={19} /></span><div><h2>日期时间 <ArrowRight size={15} /> 时间戳</h2><p>同时获取秒级与毫秒级结果</p></div></div><form onSubmit={(e) => { e.preventDefault(); setDateReady(true); }}><label htmlFor="date-input">输入日期时间 <span>YYYY-MM-DD HH:mm:ss</span></label><div className="input-with-action"><input id="date-input" aria-label="输入日期时间" placeholder="2026-09-11 10:30:00" value={date} onChange={(e) => { setDate(e.target.value); setDateReady(false); }} /><button type="button" className="input-link" onClick={() => { setDate(current.toFormat(TIME_FORMAT)); setDateReady(true); }}>此刻</button></div><div className="form-action"><button type="submit" className="button primary" >转换为时间戳<ArrowDown size={14} /></button><button type="button" className="icon-button" aria-label="清空日期时间" title="清空" onClick={() => { setDate(''); setDateReady(false); }}><RotateCcw size={14} /></button></div></form><div className="time-result">{dateResult.error ? <p className="input-error" role="alert">{dateResult.error}</p> : <><div className="timestamp-result-row"><span className="time-label">秒级</span><strong>{dateResult.value?.seconds ?? '—'}</strong><CopyButton value={dateResult.value ? String(dateResult.value.seconds) : ''} notify={notify} label="复制秒级转换结果" /></div><div className="timestamp-result-row"><span className="time-label">毫秒级</span><strong>{dateResult.value?.milliseconds ?? '—'}</strong><CopyButton value={dateResult.value ? String(dateResult.value.milliseconds) : ''} notify={notify} label="复制毫秒级转换结果" /></div></>}</div></section></div><div className="timestamp-explainer"><Clock3 size={16} /><div><strong>关于 Unix 时间戳</strong><p>从 1970 年 1 月 1 日 00:00:00 UTC 起经过的时间。时间戳本身与时区无关，时区决定日期时间的显示与解读。</p></div></div></div>
    <div className="page-note"><span><Globe2 size={13} />切换时区后，转换结果同步更新</span><span>Enter 转换</span></div>
  </div>;
}
